# -*- coding: utf-8 -*-
"""
Automatische Evaluation der Ore-Detection gegen manuelle Ground-Truth-Boxen.
"""

import argparse
import contextlib
import io
import json
import os
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

from config import DATA_DIR, OreDetectorConfig
from pipeline import OreDetector
from preprocessing import load_image

Box = Tuple[int, int, int, int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate ore detection accuracy.")
    parser.add_argument(
        "--annotations",
        default=os.path.join(DATA_DIR, "annotations", "ground_truth.json"),
        help="Path to ground-truth JSON.",
    )
    parser.add_argument(
        "--review",
        default=None,
        help="Optional manual review JSON generated by review_detections.py.",
    )
    parser.add_argument(
        "--screenshots",
        default=os.path.join(DATA_DIR, "screenshots"),
        help="Directory containing screenshots.",
    )
    parser.add_argument(
        "--iou",
        type=float,
        default=0.35,
        help="Minimum IoU for a correct detection.",
    )
    parser.add_argument(
        "--hard-iou",
        type=float,
        default=0.20,
        help="Minimum IoU for hard boxes when --include-hard is used.",
    )
    parser.add_argument(
        "--include-hard",
        action="store_true",
        help="Include boxes marked with difficulty='hard' in the scored set.",
    )
    parser.add_argument(
        "--min-f1",
        type=float,
        default=None,
        help="Fail with exit code 1 if global F1 is below this value.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show detector debug output while evaluating.",
    )
    return parser.parse_args()


def load_annotations(path: str) -> Dict[str, List[dict]]:
    if not os.path.exists(path):
        return {}

    with open(path, "r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError("Ground-truth JSON must be an object keyed by filename.")

    return data


def load_review(path: Optional[str]) -> Dict[str, dict]:
    if path is None or not os.path.exists(path):
        return {}

    with open(path, "r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError("Manual review JSON must be an object keyed by filename.")

    return data


def normalize_label(label: str) -> str:
    return label.strip().lower()


def detection_key(detection: dict) -> str:
    x, y, w, h = detection["box"]
    label = normalize_label(detection["label"])
    return f"{label}:{int(x)},{int(y)},{int(w)},{int(h)}"


def miss_key(item: dict) -> str:
    x, y, w, h = item["box"]
    label = normalize_label(item["label"])
    return f"{label}:{int(x)},{int(y)},{int(w)},{int(h)}"


def box_iou(box_a: Box, box_b: Box) -> float:
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b

    ax2 = ax + aw
    ay2 = ay + ah
    bx2 = bx + bw
    by2 = by + bh

    ix1 = max(ax, bx)
    iy1 = max(ay, by)
    ix2 = min(ax2, bx2)
    iy2 = min(ay2, by2)

    iw = max(0, ix2 - ix1)
    ih = max(0, iy2 - iy1)
    intersection = iw * ih
    union = aw * ah + bw * bh - intersection

    if union <= 0:
        return 0.0

    return intersection / float(union)


def precision_recall_f1(tp: int, fp: int, fn: int) -> Tuple[float, float, float]:
    precision = tp / float(tp + fp) if tp + fp > 0 else 0.0
    recall = tp / float(tp + fn) if tp + fn > 0 else 0.0
    f1 = (
        2.0 * precision * recall / (precision + recall)
        if precision + recall > 0
        else 0.0
    )
    return precision, recall, f1


def match_image(
    ground_truth: List[dict],
    detections: List[dict],
    iou_threshold: float,
    hard_iou_threshold: float,
    include_hard: bool,
) -> Tuple[List[dict], List[dict], List[dict]]:
    gt_items = []
    ignored_items = []

    for item in ground_truth:
        normalized = {
            "label": normalize_label(item["label"]),
            "box": tuple(item["box"]),
            "matched": False,
            "source": item,
            "difficulty": item.get("difficulty", "normal"),
        }

        is_hard = normalized["difficulty"] == "hard"

        if item.get("ignore", False):
            ignored_items.append(normalized)
        elif is_hard and not include_hard:
            ignored_items.append(normalized)
        else:
            gt_items.append(normalized)

    pred_items = sorted(
        [
            {
                "label": normalize_label(item["label"]),
                "box": tuple(item["box"]),
                "score": float(item.get("score", 0.0)),
                "source": item,
            }
            for item in detections
        ],
        key=lambda item: item["score"],
        reverse=True,
    )

    true_positives = []
    false_positives = []

    for pred in pred_items:
        best_idx = None
        best_iou = 0.0

        for idx, gt in enumerate(gt_items):
            if gt["matched"]:
                continue
            if gt["label"] != pred["label"]:
                continue

            current_iou = box_iou(pred["box"], gt["box"])
            if current_iou > best_iou:
                best_iou = current_iou
                best_idx = idx

        required_iou = iou_threshold
        if best_idx is not None and gt_items[best_idx]["difficulty"] == "hard":
            required_iou = hard_iou_threshold

        if best_idx is not None and best_iou >= required_iou:
            gt_items[best_idx]["matched"] = True
            true_positives.append({
                "label": pred["label"],
                "iou": best_iou,
                "prediction": pred["source"],
                "ground_truth": gt_items[best_idx]["source"],
            })
        elif overlaps_ignored_region(pred, ignored_items, iou_threshold):
            continue
        else:
            false_positives.append(pred["source"])

    false_negatives = [
        gt["source"]
        for gt in gt_items
        if not gt["matched"]
    ]

    return true_positives, false_positives, false_negatives


def overlaps_ignored_region(
    prediction: dict,
    ignored_items: List[dict],
    iou_threshold: float,
) -> bool:
    """
    True, wenn eine Detektion in einer nicht bewerteten Region liegt.

    Damit werden Treffer auf bewusst ausgeklammerten oder im Strict-Modus
    schwierigen Boxen nicht als False Positives bestraft.
    """

    pred_label = prediction["label"]
    pred_box = prediction["box"]

    for ignored in ignored_items:
        ignored_label = ignored["label"]
        same_label = ignored_label in {"any", "*"} or ignored_label == pred_label

        if not same_label:
            continue

        if box_iou(pred_box, ignored["box"]) >= iou_threshold:
            return True

    return False


def evaluate(args: argparse.Namespace) -> int:
    annotations = load_annotations(args.annotations)
    manual_review = load_review(args.review)

    if not annotations:
        print(f"No annotations found in {args.annotations}")
        print("Create them with: python src/annotate.py --image test1.png")
        return 1

    totals = {"tp": 0, "fp": 0, "fn": 0}
    per_label = defaultdict(lambda: {"tp": 0, "fp": 0, "fn": 0})
    evaluated_images = 0

    for filename in sorted(annotations.keys()):
        image_path = os.path.join(args.screenshots, filename)

        if not os.path.exists(image_path):
            print(f"[WARN] Missing image for annotation: {filename}")
            continue

        img = load_image(image_path)
        config = OreDetectorConfig(image_path=image_path, save_debug_masks=False)
        detector = OreDetector(config)

        if args.verbose:
            result = detector.detect(img)
        else:
            with contextlib.redirect_stdout(io.StringIO()):
                result = detector.detect(img)

        tp, fp, fn = match_image(
            annotations[filename],
            result.detections,
            args.iou,
            args.hard_iou,
            args.include_hard,
        )
        tp, fp, fn = apply_manual_review(
            filename,
            tp,
            fp,
            fn,
            manual_review,
        )

        totals["tp"] += len(tp)
        totals["fp"] += len(fp)
        totals["fn"] += len(fn)

        for item in tp:
            per_label[item["label"]]["tp"] += 1
        for item in fp:
            per_label[normalize_label(item["label"])]["fp"] += 1
        for item in fn:
            per_label[normalize_label(item["label"])]["fn"] += 1

        evaluated_images += 1
        precision, recall, f1 = precision_recall_f1(len(tp), len(fp), len(fn))
        print(
            f"{filename}: "
            f"TP={len(tp)} FP={len(fp)} FN={len(fn)} "
            f"P={precision:.3f} R={recall:.3f} F1={f1:.3f}"
        )

    precision, recall, f1 = precision_recall_f1(
        totals["tp"],
        totals["fp"],
        totals["fn"],
    )

    print("\n=== Overall ===")
    print(f"Images: {evaluated_images}")
    print(
        f"TP={totals['tp']} FP={totals['fp']} FN={totals['fn']} "
        f"P={precision:.3f} R={recall:.3f} F1={f1:.3f}"
    )

    print("\n=== By Label ===")
    for label in sorted(per_label.keys()):
        values = per_label[label]
        label_precision, label_recall, label_f1 = precision_recall_f1(
            values["tp"],
            values["fp"],
            values["fn"],
        )
        print(
            f"{label:9s} "
            f"TP={values['tp']:3d} FP={values['fp']:3d} FN={values['fn']:3d} "
            f"P={label_precision:.3f} R={label_recall:.3f} F1={label_f1:.3f}"
        )

    if args.min_f1 is not None and f1 < args.min_f1:
        print(f"\nF1 {f1:.3f} is below required minimum {args.min_f1:.3f}")
        return 1

    return 0


def apply_manual_review(
    filename: str,
    true_positives: List[dict],
    false_positives: List[dict],
    false_negatives: List[dict],
    manual_review: Dict[str, dict],
) -> Tuple[List[dict], List[dict], List[dict]]:
    image_review = manual_review.get(filename, {})
    reviewed_detections = image_review.get("detections", {})
    reviewed_misses = image_review.get("misses", {})

    tp_out = []
    fp_out = []
    fn_out = []

    for item in true_positives:
        key = detection_key(item["prediction"])
        decision = reviewed_detections.get(key, {}).get("decision")

        if decision == "invalid":
            fp_out.append(item["prediction"])
            fn_out.append(item["ground_truth"])
        else:
            tp_out.append(item)

    for item in false_positives:
        key = detection_key(item)
        decision = reviewed_detections.get(key, {}).get("decision")

        if decision == "valid":
            tp_out.append({
                "label": normalize_label(item["label"]),
                "iou": None,
                "prediction": item,
                "ground_truth": None,
                "manual": True,
            })
        elif decision == "ignore":
            continue
        else:
            fp_out.append(item)

    for item in false_negatives:
        key = miss_key(item)
        decision = reviewed_misses.get(key, {}).get("decision")

        if decision == "acceptable":
            continue

        fn_out.append(item)

    return tp_out, fp_out, fn_out


if __name__ == "__main__":
    raise SystemExit(evaluate(parse_args()))
